language: python

python:
- '2.7'
- '3.3'
- pypy

addons:
  postgresql: "9.3"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database test_database;' -U postgres
  - python manage.py syncdb
  - python manage.py migrate

script:
  - python manage.py test