language: python
python:
- '2.7'
addons:
  postgresql: '9.3'
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database test_database;' -U postgres
- python manage.py syncdb --noinput
- python manage.py migrate --noinput
- python manage.py collectstatic --noinput
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: AhkaS02OfnqZtiYULIQq5wnxQj7iAA12uS/RUezUPYcyYJrBPgo/8LtsBHTylEMM1ym1Q4el5i8/Bc/N2VekvFGWOH6ZuP1gwxYzZxIK4tTrgiJhjd+YcjhaSqV24MhyQupAJx0TzhzgOV2/uhicZSnPoJ6HYiBEXVsxMtIv6m0=
  app: serene-waters-5463
  on:
    repo: mcassiano/samba-tech-homework
  run:
    - "python manage.py syncdb --noinput"
    - "python manage.py migrate --noinput"
    - "python manage.py collectstatic --noinput"
